language: c++

install: 
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get install -qq gfortran scons mpich2 libopenmpi-dev

env:
 global:
  - OMP_NUM_THREADS=4
  - ASAGI=no
  - COMPILER=gnu
  - ASSERTIONS=no
  - LAYERS=0
  - MPI=default
  - COMPILER=gnu
  - OPENMP=notasks
  - TARGET=release
  - SCENARIO=darcy
  - FLUX_SOLVER=upwind
  - LAYERS=0
 matrix:
  - TARGET=debug ASSERTIONS=yes
  - MPI=mpich2
  - MPI=openmpi OPENMP=notasks
  - MPI=nompi
  - OPENMP=noomp
  - SCENARIO=darcy FLUX_SOLVER=upwind LAYERS=8
  - SCENARIO=swe FLUX_SOLVER=llfbath
  - SCENARIO=swe FLUX_SOLVER=aug_riemann

before_script: 
 - scons scenario=$SCENARIO compiler=$COMPILER target=$TARGET assertions=$ASSERTIONS mpi=$MPI openmp=$OPENMP asagi=$ASAGI layers=$LAYERS flux_solver=$FLUX_SOLVER -j2

script: echo "Hi!"
