language: c++

install: 
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq gfortran scons mpich2 libopenmpi-dev mpi-default-bin

env:
 global:
  - OMP_NUM_THREADS=2
  - ASAGI=no
  - COMPILER=gnu
  - ASSERTIONS=no
  - LAYERS=0
  - MPI=default
  - COMPILER=gnu
  - OPENMP=notasks
  - TARGET=release
  - SCENARIO=darcy
  - FLUX_SOLVER=upwind
  - LAYERS=0
 matrix:
  - TARGET=debug ASSERTIONS=yes
  - MPI=mpich2
  - MPI=openmpi OPENMP=noomp
  - MPI=nompi
  - SCENARIO=darcy FLUX_SOLVER=upwind LAYERS=8
  - SCENARIO=swe FLUX_SOLVER=llfbath
  - SCENARIO=swe FLUX_SOLVER=aug_riemann

before_script: 
 - scons exe=samoa_test machine=SSE4.2 scenario=$SCENARIO compiler=$COMPILER target=$TARGET assertions=$ASSERTIONS mpi=$MPI openmp=$OPENMP asagi=$ASAGI layers=$LAYERS flux_solver=$FLUX_SOLVER -j2

script:
 - if [[ "$MPI" == "nompi" ]] ; then 
     if [[ "$OPENMP" == "noomp" ]] ; then 
       bin/samoa_test -dmax 8 -threads 1 -sections 4 -tmax -1.0 -nmax 10 -output_dir . ; 
     else 
       bin/samoa_test -dmax 8 -threads 2 -sections 2 -tmax -1.0 -nmax 10 -output_dir . ; 
     fi ; 
   else 
     mpiexec -n 2 bin/samoa_test -dmax 8 -threads 1 -sections 2 -tmax -1.0 -nmax 10 -output_dir . ; 
   fi
 
