scenario='swe'
swe_dg_order='1'
#swe_dg_basis='bernstein_l2'
swe_dg_basis='bernstein_nodal'
#swe_scenario='splashing_pool'
#swe_scenario='gaussian_curve'
#swe_scenario='resting_lake'
#swe_scenario='oscillating_lake'
swe_scenario='radial_dam_break'
#swe_scenario='linear_dam_break'
#swe_dg_basis='bernstein_nodal'
flux_solver='hlle'
compiler='gnu'
asagi='false'
mpi='nompi'
target='debug'
data_refinement='sample'


