version: '3'

services:
  samoa_gnu:
    image: registry.chrz.de/chonal/docker_samoa:gnu
    build: 
      context: ../..
      dockerfile: ./scripts/docker/Dockerfile.gnu
    volumes:
      - ../../src:/app/samoa/src:rw
      - ../../SConstruct:/app/samoa/SConstruct:ro
      - ../../site_scons:/app/samoa/site_scons:ro
      - ./my_conf_gnu.py:/app/samoa/my_conf_gnu.py:ro
      - ../../bin:/app/samoa/bin:rw
      - ../../output:/app/samoa/output:rw
      - ./run_samoa_local.sh:/app/samoa/run_samoa_local.sh:ro
      - ../../scripts/FlashAnalysis/verification/data:/app/samoa/scripts/FlashAnalysis/verification/data:ro
      - /opt/samoa:/opt/samoa:rw
      - /mnt/scratch:/mnt/scratch:rw
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    shm_size: '32gb'

  samoa_intel:
    image: registry.chrz.de/chonal/docker_samoa:intel
    build: 
      context: ../..
      dockerfile: ./scripts/docker/Dockerfile.intel
    volumes:
      - ../../src:/app/samoa/src/:rw
      - ../../SConstruct:/app/samoa/SConstruct:ro
      - ../../site_scons:/app/samoa/site_scons:ro
      - ./my_conf_intel.py:/app/samoa/my_conf_intel.py:ro
      - ../../bin:/app/samoa/bin:rw
      - ../../output:/app/samoa/output:rw
      - ./run_samoa_local.sh:/app/samoa/run_samoa_local.sh:ro
      - ../../scripts/FlashAnalysis/verification/data:/app/samoa/scripts/FlashAnalysis/verification/data:ro
      - /opt/samoa:/opt/samoa:rw
      - /mnt/scratch:/mnt/scratch:rw
    shm_size: '32gb'